version: '3.6'

services:
  # mongo service
  chance-mongodb-local:
    image: mongo:latest
    container_name: chance-mongodb-local
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo_net
  chance-redis-local:
    image: 'redis:alpine'
    container_name: chance-redis-local
    ports:
      - '6379:6379'
    expose:
      - 6379
    volumes:
      - redis-data:/var/lib/redis
      - redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=password
    restart: always

volumes:
  mongo-data:
  redis-data:
  redis.conf:

networks:
  mongo_net:
    driver: bridge
